#!/bin/bash
set -eu

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
language=$YNH_APP_ARG_LANGUAGE
vboxuser="vbox"
vboxpassword=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c10)
vboxip=$YNH_APP_ARG_VBOXIP
vboxport="18083"

# Source YunoHost helpers
source /usr/share/yunohost/helpers

ynh_app_setting_set "$app" admin "$admin"
ynh_app_setting_set "$app" language "$language"

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"


# check dependances
if ! ynh_package_is_installed "php-pear" ; then
  ynh_package_install "php-pear"
fi

if ! ynh_package_is_installed "unzip" ; then
  ynh_package_install "unzip"
fi

# Copy source files
src_path=/var/www/$app
datadir=/home/yunohost.$app/

wget  -q http://freefr.dl.sourceforge.net/project/phpvirtualbox/phpvirtualbox-5.0-5.zip
unzip phpvirtualbox-5.0-5.zip
sudo mkdir $src_path
sudo mv phpvirtualbox-5.0-5/* $src_path/

# Modifiy Phpvirtualbox conf
vbox_conf=../conf/config.php-example
sed -i "s@VBOX_IP@$vboxip@g" $vbox_conf
sed -i "s@VBOX_PORT@$vboxport@g" $vbox_conf
sed -i "s@VBOX_USER@$vboxuser@g" $vbox_conf
sed -i "s@VBOX_PASSWORD@$vboxpassword@g" $vbox_conf
sed -i "s@LANGUAGE@$language@g" $vbox_conf
sudo cp $vbox_conf  $src_path/config.php
pwd

# Modify Nginx configuration file and copy it to Nginx conf directory
nginx_conf=../conf/nginx.conf
sed -i "s@YNH_WWW_PATH@$path@g" $nginx_conf
sed -i "s@YNH_WWW_ALIAS@$src_path/@g" $nginx_conf
sed -i "s@YNH_WWW_APP@$app@g" $nginx_conf
sudo cp $nginx_conf /etc/nginx/conf.d/$domain.d/$app.conf

# Modify PHP-fpm
phpfpm_conf=../conf/php-fpm.conf
sed -i "s@YNH_WWW_APP@$app@g" $phpfpm_conf
sed -i "s@YNH_WWW_ALIAS@$src_path/@g" $phpfpm_conf
finalphpconf=/etc/php5/fpm/pool.d/$app.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf
sudo chown -R www-data:www-data $src_path
# Reload services
sudo service php5-fpm reload
sudo service nginx reload

# Installation de virtualbox 

sudo sh -c "echo 'deb http://download.virtualbox.org/virtualbox/debian jessie contrib' >> /etc/apt/sources.list.d/virtualbox.list"
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get install virtualbox-5.0 --no-install-recommends -y
wget -q http://download.virtualbox.org/virtualbox/5.0.40/Oracle_VM_VirtualBox_Extension_Pack-5.0.40-115130.vbox-extpack
yes | VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.0.40-115130.vbox-extpack
sudo useradd -p $vboxpassword -d $(mkpasswd $datadir) -m -g vboxusers -s /bin/bash $vboxuser
sudo sh -c "echo "VBOXWEB_USER=vbox" > /etc/default/virtualbox"
sudo sh -c "echo "VBOXWEB_HOST=127.0.0.1" >> /etc/default/virtualbox"
mv ../conf/vboxweb.init /etc/init.d/vboxweb
chmod +x   /etc/init.d/vboxweb
sudo update-rc.d vboxweb defaults
wget -q -P $datadir http://download.virtualbox.org/virtualbox/5.0.40/VBoxGuestAdditions_5.0.40.iso
chown -R vbox: "$datadir"
/etc/init.d/vboxweb