#!/bin/bash

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# stop & uninstall virtualbox
# il faudra surement gerer l'extinction des machines allumé par la suite

VBoxManage extpack uninstall "Oracle VM VirtualBox Extension Pack"
sudo service vboxweb_ynh stop
sudo rm /lib/systemd/system/vboxweb_ynh.service
sudo rm /etc/default/virtualbox 
sudo apt-get purge -y virtualbox-*

# Remove webapps
sudo rm -rf /var/www/$app

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf

# Remove vbox user et vboxusers group
sudo deluser vbox
sudo delgroup vboxusers

# Reload nginx service
sudo service php5-fpm reload
sudo service nginx reload
