#!/bin/bash

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# stop & uninstall virtualbox
# il faudra surement gerer l'extinction des machines allumé par la suite

killall vboxwebserv
rm /etc/init.d/vboxwebserv
rm /etc/default/virtualbox 
apt-get purge virtualbox-5.0

# Remove webapps
sudo rm -rf /var/www/$app

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf
# Reload nginx service
sudo service php5-fpm reolad
sudo service nginx reload
